[tool.poetry]
name = "bomberman_rl"
version = "0.1.0"
description = "Pack"
authors = ["Aileen Reichelt", "Ivo Schaper", "Kieu Trang Nguyen Vu"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.2"
pygame = "^2.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
